zephyr: fix build error
__set_MSP is undefined because AST10x0 SOC code doesn't include cmsis.h.
Need to fix kernel code in the future but for now we just add include
path in mcuboot/main.c

```
undefined reference to `__set_MSP'
```
Signed-off-by: Dylan Hung <dylan_hung@aspeedtech.com>
Change-Id: I42282dfaf98aee99cba0da81906f71a0a9b36599